### ISSUE TITLE
/api/admin/email/templates/{id}

### ISSUE THREAD

**Issue by MarcoHanisch** [swp-unikat/Einschreibesystem#154]
"code": 500,
  "message": "Attempted to load class \"Codes\" from namespace \"Core\\APIBundle\\Controller\\Admin\".\nDid you forget a \"use\" statement for \"FOS\\RestBundle\\Util\\Codes\"?"

Funktion funktioniert und Emailtemplate wird gelöscht

**Comment by ljbergmann** [comment]
fixed in  fc3ac79
