### ISSUE TITLE
 GET /api/admin/admin/{email}/admin/invite 

### ISSUE THREAD

**Issue by MarcoHanisch** [swp-unikat/Einschreibesystem#189]
"code": 500,
  "message": "Variable \"participant\" does not exist in \"__string_template__c6b1a2b0117f0ab28c5e3f9fc19b82b9e7e5a5fe8e9a67b59d8a6a5d7d3cac5c\" at line 1"

**Comment by ljbergmann** [comment]
fixed at  8350471
