### ISSUE TITLE
Create new user, directory not writable

### ISSUE THREAD

**Issue by DirkHeinke** [swp-unikat/Einschreibesystem#205]
When I try to create a new user, I receive an error about write permissions in `/var/www/app/cache/dev/annotations`

```
vagrant@vagrant-ubuntu-trusty-64:/var/www$ php app/console fos:user:create
Please choose a username:dirk
Please choose an email:dirk.heinke@tu-ilmenau.de
Please choose a password:

                                                                       
  [InvalidArgumentException]                                           
  The directory "/var/www/app/cache/dev/annotations" is not writable.  
                                                                       
```

**Comment by ljbergmann** [comment]
Normally  a simple 
```bash
cd /var/www
chmod 777  -R app/cache/*
```
should fix that.

**Comment by DirkHeinke** [comment]
`sudo -i` (becomming root) fixes it as well, but I'm not sure if that is the right way. 777 is mostly a bad permission. Anyways, if that is the desired fix, please add it to provisioning.

**Comment by ljbergmann** [comment]
After some testing, this might be the better solution
```bash
chown www-data:www-data /var/www/* -R
```

**Comment by DirkHeinke** [comment]
In the vagrant box you are _vagrant_ and you can't switch to _www-data_ user.

**Comment by ljbergmann** [comment]
This only modifies the file owern & group. Switching to the www-data user is not necessary.
