### ISSUE TITLE
Error 404 on workshops/x/waitinglist

### ISSUE THREAD

**Issue by DirkHeinke** [swp-unikat/Einschreibesystem#250]
The waitinglist does not show up and the call to the api fails with 404.

**Comment by ljbergmann** [comment]
According to the api doku this is the correct respond if there are no participants on the waitinglist.
```
{
  "code": 404,
  "message": "No waitinglist for workshop"
}
```

**Comment by DirkHeinke** [comment]
I would suggest using 204 instead: `204 No Content` https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.5
